### ISSUE TITLE
Fails loading wait times 

### ISSUE THREAD

**Issue by mccarthyk** [Commbocc/CenterPass#19]
The [CenterPass](https://www.hillsboroughcounty.org/businesses/permits-and-records/centerpass) page is failing to load wait times.

```
Error in fetch TypeError: t.Unit.Service.map is not a function
    at HcCenterpass.umd.min.js:16:65476
```

[https://github.com/Commbocc/CenterPass/blob/master/src/models/Service.js#L44](https://github.com/Commbocc/CenterPass/blob/master/src/models/Service.js#L44)

**Comment by mccarthyk** [comment]
@JordanPisani QFlow documentation:

- [Internet Wait Times Module.docx](https://github.com/Commbocc/CenterPass/files/8226827/Internet.Wait.Times.Module.docx)
- [IWT Product Guide - Version 4.02.docx](https://github.com/Commbocc/CenterPass/files/8226828/IWT.Product.Guide.-.Version.4.02.docx)

**Comment by JordanPisani** [comment]
Removed WaitTimes component and referencing bullet point from Sitecore wysiwyg.
